apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project_cicd
  template:
    metadata:
      labels:
        app: project_cicd
    spec:
      containers:
        - name: project_cicd
          image: rajith08/project_cicd:1.0.0-10
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
