apiVersion: v1
kind: Service
metadata:
  name: project_cicd
  labels:
    app: project_cicd
spec:
  selector:
    app: project_cicd

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
